apiVersion: apps/v1
kind: Deployment
metadata:
  name: savannah-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savannah-backend
  template:
    metadata:
      labels:
        app: savannah-backend
    spec:
      containers:
        - name: savannah-backend
          image: kipchumbarodgers/savannah-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: savannah-secrets
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: savannah-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: savannah-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: postgres
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DJANGO_SECRET_KEY
