apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: django-insecure-(63rurtw#p9#tz#8%9^n=vi^8h=+6e8yz003cagxswo$3=fqsr
  DB_NAME: savannah_db
  DB_USER: savannah_user
  DB_PASSWORD: savannah_password
  DB_HOST: postgres
