apiVersion: v1
kind: Service
metadata:
  name: savannah-backend-service
spec:
  selector:
    app: savannah-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
